[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
rustyline = "17.0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde_json = "1.0"
